#!/bin/bash
# This is our first script.
echo 'Begin!'
source activate dense
for i in {0..852}
do
    /home/cjy/.conda/envs/dense/bin/python2.7 /home/cjy/GNN_demo/hand_GNN.py $i 10 0.001 1 2 1
done

for i in {0..852}
do
    /home/cjy/.conda/envs/dense/bin/python2.7 /home/cjy/GNN_demo/hand_GNN.py $i 10 0.0001 1 2 1
done

for i in {0..852}
do
    /home/cjy/.conda/envs/dense/bin/python2.7 /home/cjy/GNN_demo/hand_GNN.py $i 10 0.00001 1 2 1
done

